[package]
name = "rust_class_project"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.15", features = ["blocking"] }
rust-fetch = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
